// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlRdCBqiz0NX_CQaSBmFMejyxVwB67cZM',
    appId: '1:502418806880:web:f78157f69731945de40b05',
    messagingSenderId: '502418806880',
    projectId: 'notification-9d661',
    authDomain: 'notification-9d661.firebaseapp.com',
    storageBucket: 'notification-9d661.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVBzCxP_QcIT2vDicxwK1HeN--QCqJS-0',
    appId: '1:502418806880:android:ca832d4ac728d029e40b05',
    messagingSenderId: '502418806880',
    projectId: 'notification-9d661',
    storageBucket: 'notification-9d661.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP7bGZdW9jei2O315zZsSRd6hhCvyEsBU',
    appId: '1:502418806880:ios:3c30580b382746e7e40b05',
    messagingSenderId: '502418806880',
    projectId: 'notification-9d661',
    storageBucket: 'notification-9d661.appspot.com',
    iosBundleId: 'com.example.webApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP7bGZdW9jei2O315zZsSRd6hhCvyEsBU',
    appId: '1:502418806880:ios:e73f1c0bb217da84e40b05',
    messagingSenderId: '502418806880',
    projectId: 'notification-9d661',
    storageBucket: 'notification-9d661.appspot.com',
    iosBundleId: 'com.example.webApp.RunnerTests',
  );
}
